name: notes_app
description: Приложение заметок
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  drift: ^2.20.0
  drift_flutter: ^0.2.4
  lottie: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.0
  drift_dev: ^2.20.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true
  assets:
    - assets/